require("modules.monitors")
require("modules.autostart")
require("modules.envs")
require("modules.style")
require("modules.input_devices")
require("modules.keybinds")
require("modules.windowrules")
require("modules.animations")
