[General]
background=/home/philip/Pictures/Wallpapers/current_wallpaper.jpg

# Colors
accentColor=#A9C78F
backgroundColor=#1A1C18
textColor=#E3E3DC
autoColor=true
use24HourClock=true

# Font family. Override with any installed system font.
fontFamily=Google Sans Flex
fontSize=12
